.PHONY: clean All

All:
	@echo "----------Building project:[ FinalProject809Y - Debug ]----------"
	@cd "FinalProject809Y" && "$(MAKE)" -f  "FinalProject809Y.mk"
clean:
	@echo "----------Cleaning project:[ FinalProject809Y - Debug ]----------"
	@cd "FinalProject809Y" && "$(MAKE)" -f  "FinalProject809Y.mk" clean
