Maze Solver: Maze Class Reference
Maze Class Reference
#include <maze.h>
Public Member Functions
Maze ()
void displayMaze (int)
This function uses a series of loops to display the maze with borders and numbering.
bool isObstacle (int, int, MobileRobot *)
This function checks if the input position is blocked by an obstacle of some sort.
bool isGoal (MobileRobot *, std::vector< int >)
This function compares the robot position to its target goal.
std::vector< int > isInputValid (int, int)
This function iteratively checks if the input is a valid open position in the maze.
void changeSpace (std::vector< int >, char)
This function overwrites an input maze position with a character.
void rewrite (MobileRobot *, MobileRobot *, std::vector< int >, std::vector< int >)
This function cleans up the wrong turn markers found in the maze from backtracking.
std::vector< int > numericInputs ()
This function checks that all inputs are valid numbers.
Public Attributes
char maze_arr [31][46]
This is the 31x46 character array that represents the hard-coded maze.
Private Attributes
int n
int m
Friends
class MobileRobot
Detailed Description
Author
Ari Kupferberg, Bharat Mathur, Brenda Scheufele, Jagadesh Nagireddi, Raja Iskala
Date
20/05/19
Definition at line 15 of file maze.h.
Constructor & Destructor Documentation
Maze::Maze ()
Definition at line 12 of file maze.cpp.
References m, and n.
            {
     n = 31;
     m = 46;
 }
Member Function Documentation
void Maze::displayMaze (int q)
This function uses a series of loops to display the maze with borders and numbering.
Parameters
q Choice integer
Returns
None
Definition at line 104 of file maze.cpp.
References m, maze_arr, and n.
Referenced by main().
{
     cout << "\n    ---";
     for (int j=0; j<m; ++j)
         cout << "--";
     for (int i=0; i<n; ++i) {
         if (i<10)
             cout << "\n  " << i << " | ";
         else
             cout << "\n " << i << " | ";
         for (int j=0; j<m; ++j)
             cout << maze_arr[i][j] << " ";
         cout << "|";
     }
     cout << "\n    ---";
     for (int j=0; j<m; ++j)
         cout << "--";
     cout << "\n      ";
     int h = 0; int k = 1;
     for (int j=0; j<m; ++j) {
         if (j<10)
             cout << j << " ";
         else {
             if (h==10) {
                 k++;
                 h=0;
             }
             cout << k << " ";
             h++;
         }
     }
     cout << "\n                          ";
     for (int i=0; i<3; i++) {
         for (int j=0; j<10; j++)
             cout << j << " ";
     }
     cout << "0 1 2 3 4 5";
     cout << endl;
     if (q == 1) {
         cout << "Symbols:\n' ' = open\n'#' = blocked\n't' = start for tracked robot\n'w' = start for wheeled robot\n";
         cout << "'|' = path for wheeled robot\n'-' = path for tracked robot\n'+' = overlapping paths\n";
         cout << "'b' = bottle target\n'p' = plate target\n";
     }
     cout << endl;
 }
bool Maze::isObstacle (int x, int y, MobileRobot * robot)
This function checks if the input position is blocked by an obstacle of some sort.
Parameters
x,y The 2D coordinates of position
robot A pointer to the robot in question
Returns
Boolean
Definition at line 17 of file maze.cpp.
References MobileRobot::getVisitedMarker(), MobileRobot::getWrongTurnMarker(), maze_arr, and n.
Referenced by findPath().
{
     if ( maze_arr[x][y] == '#' || maze_arr[x][y] == robot->getWrongTurnMarker() || maze_arr[x][y] == robot->getVisitedMarker())
         return true;
     if ( maze_arr[x][y] == '+' || maze_arr[x][y] == 'T' || x>=n)
         return true;
     return false;
 }
bool Maze::isGoal (MobileRobot * robot, std::vector< int > goal)
This function compares the robot position to its target goal.
Parameters
robot A pointer to the robot in question
goal The position of the target goal
Returns
Boolean
Definition at line 25 of file maze.cpp.
References MobileRobot::getRobotLoc().
Referenced by findPath().
{
     if(robot->getRobotLoc() == goal) {
         return true;
     } else {
         return false;
     }
 }
std::vector< int > Maze::isInputValid (int x, int y)
This function iteratively checks if the input is a valid open position in the maze.
Parameters
x,y The 2D coordinates of position
Returns
Vector of confirmed position
Definition at line 33 of file maze.cpp.
References m, maze_arr, and n.
Referenced by connectTarget(), and numericInputs().
{
     while( maze_arr[x][y]=='#' || x<0 || x>=n || y<0 || y>=m ) {
         cout<< "Invalid input, position is obstacle or outside maze. Please enter different coordinates: ";
         cin >> x >> y;
     }
     std::vector<int> vec;
     vec.push_back(x);
     vec.push_back(y);
     return vec;
 }
void Maze::changeSpace (std::vector< int > xy, char z)
This function overwrites an input maze position with a character.
Parameters
xy The vector for the maze position
z The character to overwrite in the maze
Returns
None
The many "if" statements in this function account for the different possible characters that can already occupy the space to be overwritten. If it's part of the robot's path, and the other robot has crossed that path, a '+' is used. If the robot is backtracking, and the other robot has crossed that path, a 'T' is used. If both robots have backtracked, a 'Z' is used. If both robot start positions are the same, an 'S' is used, and if the targets are the same, a 'G' is used. These conditions ensure that the second robot does not erase the first robot's path.
Definition at line 51 of file maze.cpp.
References maze_arr.
Referenced by findPath(), and rewrite().
{
     int x = xy[0]; int y = xy[1];
     if (z=='|') {
         if (maze_arr[x][y] == '-')
             maze_arr[x][y] = '+';
         else if (maze_arr[x][y] == '+')
             maze_arr[x][y] = '+';
         else
             maze_arr[x][y] = z;
     }
     else if (z=='Y') {
         if (maze_arr[x][y] == '-' || maze_arr[x][y] == '+')
             maze_arr[x][y] = 'T';
         else
             maze_arr[x][y] = z;
     }
     else if (z=='w') {
         if (maze_arr[x][y] == 't')
             maze_arr[x][y] = 'S';
         else
             maze_arr[x][y] = z;
     }
     else if (z=='b') {
         if (maze_arr[x][y] == 'p')
             maze_arr[x][y] = 'G';
         else
             maze_arr[x][y] = z;
     }
     else
         maze_arr[x][y] = z;
 }
void Maze::rewrite (MobileRobot * robot, MobileRobot * robot2, std::vector< int > plate, std::vector< int > bottle)
This function cleans up the wrong turn markers found in the maze from backtracking.
Parameters
robot A pointer to the tracked robot
robot2 A pointer to the wheeled robot
plate The plate target, passed by reference
bottle The bottle target, passed by reference
Returns
None
The function looks for any of the three markers that represent only a wrong turn space, and replaces that character with an open space. If a 'T' if found, that means that it is a right path for the tracked robot and wrong turn for the wheeled robot, so the tracked robot path character '-' is replaced. Finally, the start positions of the robots, and the target positions are placed in at the end.
Definition at line 89 of file maze.cpp.
References changeSpace(), MobileRobot::getStart(), MobileRobot::getStartMarker(), and maze_arr.
Referenced by main().
{
     for (int i=0; i<31; i++) {
         for (int j=0; j<46; j++) {
             if (maze_arr[i][j] == 'X' || maze_arr[i][j] == 'Y')
                  maze_arr[i][j] = ' ';
             if (maze_arr[i][j] == 'T')
                  maze_arr[i][j] = '-';
         }
     }
     changeSpace(robot->getStart(),robot->getStartMarker());
     changeSpace(robot2->getStart(),robot2->getStartMarker());
     changeSpace(plate,'p');
     changeSpace(bottle,'b');
 }
std::vector< int > Maze::numericInputs ()
This function checks that all inputs are valid numbers.
Returns
Vector of confirmed numeric inputs
Definition at line 150 of file maze.cpp.
References isInputValid().
Referenced by main(), TrackedRobot::TrackedRobot(), and WheeledRobot::WheeledRobot().
{
     int input1, input2;
     cin >> input1 >> input2;
     while(!cin) {
         cin.clear(); // reset failbit
         cin.ignore(1000,'\n'); //skip bad input
         cout << "Invalid Entry, non-numeric input. Please reenter the two inputs: ";
         cin >> input1 >> input2;
     }
     std::vector<int> inputs;
     inputs = isInputValid(input1, input2);
     cout << "[" << inputs[0] << "," << inputs[1] << "]" << endl;
     return inputs;
 }
Friends And Related Function Documentation
friend class MobileRobot friend
Definition at line 19 of file maze.h.
Member Data Documentation
int Maze::n private
Definition at line 17 of file maze.h.
Referenced by displayMaze(), isInputValid(), isObstacle(), and Maze().
int Maze::m private
Definition at line 18 of file maze.h.
Referenced by displayMaze(), isInputValid(), and Maze().
char Maze::maze_arr[31][46]
Initial value:
=
    {{'#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#'},
    {'#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#','#','#','#',' ',' ','#'},
    {'#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#'},
    {'#',' ',' ','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#'},
    {'#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ','#',' ',' ','#'},
    {'#',' ',' ','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#',' ',' ','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#',' ',' ','#'},
    {'#',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#',' ',' ','#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','#'},
    {'#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#',' ',' ','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#','#'}}
This is the 31x46 character array that represents the hard-coded maze.
Definition at line 23 of file maze.h.
Referenced by changeSpace(), displayMaze(), isInputValid(), isObstacle(), and rewrite().
The documentation for this class was generated from the following files:
Maze/maze.h
Maze/maze.cpp