Maze Solver: MobileRobot Class Reference
MobileRobot Class Reference abstract
#include <mobilerobot.h>
Public Member Functions
virtual void setTargetLoc (std::vector< int >)=0
This is a pure virtual method definition for a setter for the target position.
virtual void setRobotLoc (std::vector< int >)=0
This is a pure virtual method definition for a setter for the robot current position.
virtual std::string getName ()=0
This is a pure virtual method definition for a getter for the robot name.
virtual std::vector< int > getStart ()=0
This is a pure virtual method definition for a getter for the robot start position.
virtual std::vector< int > getRobotLoc ()=0
This is a pure virtual method definition for a getter for the robot current position.
virtual std::vector< int > getTargetLoc ()=0
This is a pure virtual method definition for a getter for the robot's target position.
virtual char getStartMarker ()=0
This is a pure virtual method definition for a getter for the robot start marker.
virtual char getVisitedMarker ()=0
This is a pure virtual method definition for a getter for the robot path marker.
virtual char getWrongTurnMarker ()=0
This is a pure virtual method definition for a getter for the robot backtracking marker.
virtual std::vector< int > checkTarget (std::vector< int >)=0
This is a pure virtual method definition for checking the validity of the target position.
virtual std::vector< int > Up (int, int)=0
This is a pure virtual method definition for obtaining the 'UP' position for the robots.
virtual std::vector< int > Down (int, int)=0
This is a pure virtual method definition for obtaining the 'DOWN' position for the robots.
virtual std::vector< int > Right (int, int)=0
This is a pure virtual method definition for obtaining the 'RIGHT' position for the robots.
virtual std::vector< int > Left (int, int)=0
This is a pure virtual method definition for obtaining the 'LEFT' position for the robots.
virtual void update (std::string)=0
This is a pure virtual method definition for updating the stack with the robot state.
std::stack< char > reverseStack (std::stack< char >)
This function reverses the list of robot states in the stack.
Public Attributes
std::stack< char > state_stack
Stack variable of type character for the list of robot states.
Friends
class Maze
Detailed Description
Author
Ari Kupferberg, Bharat Mathur, Brenda Scheufele, Jagadesh Nagireddi, Raja Iskala
Date
20/05/19
Definition at line 17 of file mobilerobot.h.
Member Function Documentation
virtual void MobileRobot::setTargetLoc (std::vector< int >) pure virtual
This is a pure virtual method definition for a setter for the target position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by connectTarget().
virtual void MobileRobot::setRobotLoc (std::vector< int >) pure virtual
This is a pure virtual method definition for a setter for the robot current position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual std::string MobileRobot::getName () pure virtual
This is a pure virtual method definition for a getter for the robot name.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual std::vector<int> MobileRobot::getStart () pure virtual
This is a pure virtual method definition for a getter for the robot start position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by Maze::rewrite().
virtual std::vector<int> MobileRobot::getRobotLoc () pure virtual
This is a pure virtual method definition for a getter for the robot current position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath(), and Maze::isGoal().
virtual std::vector<int> MobileRobot::getTargetLoc () pure virtual
This is a pure virtual method definition for a getter for the robot's target position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath(), and main().
virtual char MobileRobot::getStartMarker () pure virtual
This is a pure virtual method definition for a getter for the robot start marker.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by Maze::rewrite().
virtual char MobileRobot::getVisitedMarker () pure virtual
This is a pure virtual method definition for a getter for the robot path marker.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath(), and Maze::isObstacle().
virtual char MobileRobot::getWrongTurnMarker () pure virtual
This is a pure virtual method definition for a getter for the robot backtracking marker.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath(), and Maze::isObstacle().
virtual std::vector<int> MobileRobot::checkTarget (std::vector< int >) pure virtual
This is a pure virtual method definition for checking the validity of the target position.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by connectTarget().
virtual std::vector<int> MobileRobot::Up (int , int) pure virtual
This is a pure virtual method definition for obtaining the 'UP' position for the robots.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual std::vector<int> MobileRobot::Down (int , int) pure virtual
This is a pure virtual method definition for obtaining the 'DOWN' position for the robots.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual std::vector<int> MobileRobot::Right (int , int) pure virtual
This is a pure virtual method definition for obtaining the 'RIGHT' position for the robots.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual std::vector<int> MobileRobot::Left (int , int) pure virtual
This is a pure virtual method definition for obtaining the 'LEFT' position for the robots.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
virtual void MobileRobot::update (std::string) pure virtual
This is a pure virtual method definition for updating the stack with the robot state.
Implemented in TrackedRobot, and WheeledRobot.
Referenced by findPath().
std::stack< char > MobileRobot::reverseStack (std::stack< char > state_stack)
This function reverses the list of robot states in the stack.
Parameters
state_stack The stack of robot states
Returns
The reversed stack of robot states
Definition at line 15 of file mobilerobot.cpp.
Referenced by findPath().
{
     std::stack<char> reversed_stack;
     while (!state_stack.empty()) {
         reversed_stack.push(state_stack.top());
         state_stack.pop();
     }
     return reversed_stack;
 }
Friends And Related Function Documentation
friend class Maze friend
Definition at line 19 of file mobilerobot.h.
Member Data Documentation
std::stack<char> MobileRobot::state_stack
Stack variable of type character for the list of robot states.
Definition at line 21 of file mobilerobot.h.
Referenced by findPath(), WheeledRobot::update(), and TrackedRobot::update().
The documentation for this class was generated from the following files:
RobotModel/mobilerobot.h
RobotModel/mobilerobot.cpp