Maze Solver: WheeledRobot Class Reference
WheeledRobot Class Reference
#include <wheeledRobot.h>
Public Member Functions
WheeledRobot ()
WheeledRobot (Maze *)
This is a 1 args constructor.
virtual void setTargetLoc (std::vector< int > pos) override
This is an override setter for the robot's target.
virtual void setRobotLoc (std::vector< int > pos) override
This is an override setter for the robot's current position.
virtual std::string getName () override
This is an override getter for the robot's name.
virtual std::vector< int > getStart () override
This is an override getter for the robot's start position.
virtual std::vector< int > getRobotLoc () override
This is an override getter for the robot's current position.
virtual std::vector< int > getTargetLoc () override
This is an override getter for the robot's target.
virtual char getStartMarker () override
This is an override getter for the robot's start marker.
virtual char getVisitedMarker () override
This is an override getter for the robot's path marker.
virtual char getWrongTurnMarker () override
This is an override getter for the robot's backtracking marker.
virtual std::vector< int > checkTarget (std::vector< int >)
This is an override function that checks that the target does not share its position with the robot start.
virtual std::vector< int > Up (int, int)
This is an override function that obtains the "up" coordinates of the robot.
virtual std::vector< int > Down (int, int)
This is an override function that obtains the "down" coordinates of the robot.
virtual std::vector< int > Right (int, int)
This is an override function that obtains the "right" coordinates of the robot.
virtual std::vector< int > Left (int, int)
This is an override function that obtains the "left" coordinates of the robot.
virtual void update (std::string)
This function pushes the current robot state to the top of the stack.
Public Member Functions inherited from MobileRobot
std::stack< char > reverseStack (std::stack< char >)
This function reverses the list of robot states in the stack.
Private Attributes
std::string _name
std::vector< int > target
std::vector< int > start_position
std::vector< int > current_position
char start_marker = 'w'
char visited_marker = '|'
char wrong_turn = 'Y'
Additional Inherited Members
Public Attributes inherited from MobileRobot
std::stack< char > state_stack
Stack variable of type character for the list of robot states.
Detailed Description
Author
Ari Kupferberg, Bharat Mathur, Brenda Scheufele, Jagadesh Nagireddi, Raja Iskala
Date
20/05/19
Definition at line 15 of file wheeledRobot.h.
Constructor & Destructor Documentation
WheeledRobot::WheeledRobot ()
WheeledRobot::WheeledRobot (Maze * maze)
This is a 1 args constructor.
This constructor prompts the user to enter the robot starting position. It then checks that the position is a valid input for the maze, updates the start and current position of the robot, and defines the robot name.
Parameters
maze A pointer to the maze
Definition at line 14 of file wheeledRobot.cpp.
References _name, current_position, getStart(), Maze::numericInputs(), and start_position.
{
     std::cout << "Please enter the start position for the wheeled robot: ";
     start_position = maze->numericInputs();
     current_position = getStart();
     _name = "Wheeled";
 }
Member Function Documentation
virtual void WheeledRobot::setTargetLoc (std::vector< int > pos) inline override virtual
This is an override setter for the robot's target.
Parameters
pos Position to set for robot's target
Implements MobileRobot.
Definition at line 39 of file wheeledRobot.h.
Referenced by checkTarget().
 { target = pos; }
virtual void WheeledRobot::setRobotLoc (std::vector< int > pos) inline override virtual
This is an override setter for the robot's current position.
Parameters
pos Position to set for robot
Implements MobileRobot.
Definition at line 44 of file wheeledRobot.h.
 { current_position = pos; }
virtual std::string WheeledRobot::getName () inline override virtual
This is an override getter for the robot's name.
Returns
String of robot name
Implements MobileRobot.
Definition at line 49 of file wheeledRobot.h.
References _name.
 { return _name; }
virtual std::vector<int> WheeledRobot::getStart () inline override virtual
This is an override getter for the robot's start position.
Returns
Vector of robot start position
Implements MobileRobot.
Definition at line 54 of file wheeledRobot.h.
References start_position.
Referenced by checkTarget(), and WheeledRobot().
 { return start_position; }
virtual std::vector<int> WheeledRobot::getRobotLoc () inline override virtual
This is an override getter for the robot's current position.
Returns
Vector of robot current position
Implements MobileRobot.
Definition at line 59 of file wheeledRobot.h.
References current_position.
 { return current_position; }
virtual std::vector<int> WheeledRobot::getTargetLoc () inline override virtual
This is an override getter for the robot's target.
Returns
Vector of robot target position
Implements MobileRobot.
Definition at line 64 of file wheeledRobot.h.
References target.
 { return target; }
virtual char WheeledRobot::getStartMarker () inline override virtual
This is an override getter for the robot's start marker.
Returns
Character of robot start marker
Implements MobileRobot.
Definition at line 69 of file wheeledRobot.h.
References start_marker.
 { return start_marker; }
virtual char WheeledRobot::getVisitedMarker () inline override virtual
This is an override getter for the robot's path marker.
Returns
Character of robot path marker
Implements MobileRobot.
Definition at line 74 of file wheeledRobot.h.
References visited_marker.
 { return visited_marker; }
virtual char WheeledRobot::getWrongTurnMarker () inline override virtual
This is an override getter for the robot's backtracking marker.
Returns
Character of robot backtracking marker
Implements MobileRobot.
Definition at line 79 of file wheeledRobot.h.
References checkTarget(), Down(), Left(), Right(), Up(), update(), and wrong_turn.
 { return wrong_turn; }
std::vector< int > WheeledRobot::checkTarget (std::vector< int > goal) virtual
This is an override function that checks that the target does not share its position with the robot start.
Parameters
goal Vector of the target position
Returns
Vector of the confirmed target position
Implements MobileRobot.
Definition at line 21 of file wheeledRobot.cpp.
References getStart(), and setTargetLoc().
Referenced by getWrongTurnMarker().
{
     while(getStart()[0] == goal[0] && getStart()[1] == goal[1]) {
         std::cout << "Invalid: wheeled robot & target share position. Please enter different coordinates for target: ";
         std::cin >> goal[0] >> goal[1];
     }
     setTargetLoc(goal);
     return goal;
 }
std::vector< int > WheeledRobot::Up (int x, int y) virtual
This is an override function that obtains the "up" coordinates of the robot.
Parameters
x,y The 2D coordinates of current position
Returns
Vector of new coordinates
Implements MobileRobot.
Definition at line 31 of file wheeledRobot.cpp.
Referenced by getWrongTurnMarker().
{
     x=x-1;
     y=y;
     std::vector<int> up{x,y};
     return up;
 }
std::vector< int > WheeledRobot::Down (int x, int y) virtual
This is an override function that obtains the "down" coordinates of the robot.
Parameters
x,y The 2D coordinates of current position
Returns
Vector of new coordinates
Implements MobileRobot.
Definition at line 38 of file wheeledRobot.cpp.
Referenced by getWrongTurnMarker().
{
     x=x+1;
     y=y;
     std::vector<int> down{x,y};
     return down;
 }
std::vector< int > WheeledRobot::Right (int x, int y) virtual
This is an override function that obtains the "right" coordinates of the robot.
Parameters
x,y The 2D coordinates of current position
Returns
Vector of new coordinates
Implements MobileRobot.
Definition at line 45 of file wheeledRobot.cpp.
Referenced by getWrongTurnMarker().
{
     x=x;
     y=y+1;
     std::vector<int> right{x,y};
     return right;
 }
std::vector< int > WheeledRobot::Left (int x, int y) virtual
This is an override function that obtains the "left" coordinates of the robot.
Parameters
x,y The 2D coordinates of current position
Returns
Vector of new coordinates
Implements MobileRobot.
Definition at line 52 of file wheeledRobot.cpp.
Referenced by getWrongTurnMarker().
{
     x=x;
     y=y-1;
     std::vector<int> left{x,y};
     return left;
 }
void WheeledRobot::update (std::string action) virtual
This function pushes the current robot state to the top of the stack.
Parameters
action A string of the direction of the robot action
Returns
None
For the chosen of the four actions, the function creates a pointer to the respective robot state and then updates the robot stack with that state. Then the pointer is deleted to free up the space.
Implements MobileRobot.
Definition at line 63 of file wheeledRobot.cpp.
References MobileRobot::state_stack, and RobotState::update().
Referenced by getWrongTurnMarker().
{
     if (action=="up")
     {
         RobotState* state = new UpState();
         state->update(state_stack);
         delete state;
     }
     if (action=="right")
     {
         RobotState* state = new RightState();
         state->update(state_stack);
         delete state;
     }
     if (action=="down")
     {
         RobotState* state = new DownState();
         state->update(state_stack);
         delete state;
     }
     if(action=="left")
     {
         RobotState* state = new LeftState();
         state->update(state_stack);
         delete state;
     }
 }
Member Data Documentation
std::string WheeledRobot::_name private
Definition at line 17 of file wheeledRobot.h.
Referenced by getName(), and WheeledRobot().
std::vector<int> WheeledRobot::target private
Definition at line 18 of file wheeledRobot.h.
Referenced by getTargetLoc().
std::vector<int> WheeledRobot::start_position private
Definition at line 19 of file wheeledRobot.h.
Referenced by getStart(), and WheeledRobot().
std::vector<int> WheeledRobot::current_position private
Definition at line 20 of file wheeledRobot.h.
Referenced by getRobotLoc(), and WheeledRobot().
char WheeledRobot::start_marker = 'w' private
Definition at line 21 of file wheeledRobot.h.
Referenced by getStartMarker().
char WheeledRobot::visited_marker = '|' private
Definition at line 22 of file wheeledRobot.h.
Referenced by getVisitedMarker().
char WheeledRobot::wrong_turn = 'Y' private
Definition at line 23 of file wheeledRobot.h.
Referenced by getWrongTurnMarker().
The documentation for this class was generated from the following files:
RobotModel/wheeledRobot.h
RobotModel/wheeledRobot.cpp